### ISSUE TITLE
import requests

### ISSUE THREAD

**Issue by Sakatland** [tonybenoy/cocapi#4] opened 2020-03-07 07:44 UTC
Hey,

Last version has a bug, "import requests" is missing at the beginning as it is still being used on line 8:
`self.requests = requests`

Cheers and thanks for the script!

**Comment by tonybenoy** [comment] 2020-03-07 08:04
@Sakatland  the issue is fixed. Thanks for letting me know. Not sure how I missed that. I've replaced requests with httpx. So essentially This should be easier to make async api requests.

**Comment by Sakatland** [comment] 2020-03-08 03:57
A pleasure, it's a very small contribution to your great script but I'm glad to help as I'm using it very often!

**Comment by tonybenoy** [comment] 2020-03-10 13:42
@Sakatland I think the issue is resolved. I'm closing the issue. Feel free to reopen in breaking,

**Closed as completed by tonybenoy** 2020-03-10 13:42 UTC
Labels: bug
